### ISSUE TITLE
KeyError with turbines but without optimisation

### ISSUE THREAD

**Issue by ctjacobs** [OpenTidalFarm/OpenTidalFarm#18]
I'm trying to run a shallow water simulation with turbines, but without any adjoint optimisation. I'm getting the following error

```
Turbine added at (25.00, 25.00).
Turbine added at (50.00, 25.00).
Solve a transient shallow water problem
Solving linear system of size 528 x 528 (PETSc Krylov solver).
Traceback (most recent call last):
  File "turbines.py", line 48, in <module>
    for s in solver.solve():
  File "/home/ctj10/OpenTidalFarm/opentidalfarm/solvers/coupled_sw_solver.py", line 368, in solve
    elif type(farm.friction_function) == list:
  File "/home/ctj10/OpenTidalFarm/opentidalfarm/farm/base_farm.py", line 26, in friction_function
    tf = self.turbine_cache["turbine_field"]
KeyError: 'turbine_field'
```

when running 

```
#!/usr/bin/env python

from opentidalfarm import *

dx = 10.0
domain = RectangularDomain(x0=0, y0=0, x1=100, y1=50, nx=int(100/dx), ny=int(50/dx))

bcs = BoundaryConditionSet()
u_expr = Expression(("2.0", "1e-16"))
bcs.add_bc("u", u_expr, facet_id=1)
bcs.add_bc("u", u_expr, facet_id=2)
bcs.add_bc("u", Constant((DOLFIN_EPS, DOLFIN_EPS)), facet_id=3, bctype="weak_dirichlet")

# Set the shallow water parameters
prob_params = SWProblem.default_parameters()
prob_params.domain = domain
prob_params.bcs = bcs
prob_params.viscosity = Constant(3)
prob_params.depth = Constant(50)
prob_params.friction = Constant(0.0025)

prob_params.start_time = 0
prob_params.finish_time = 100.0
prob_params.dt = 10
prob_params.theta = 1.0

prob_params.initial_condition = Constant((DOLFIN_EPS, DOLFIN_EPS, DOLFIN_EPS))

turbine = BumpTurbine(diameter=20.0, friction=8.5)
farm = Farm(domain, turbine=turbine)
turbine_coordinates = [(25, 25), (50, 25)]
for coord in turbine_coordinates:
   farm.add_turbine(coord)

# Link the turbine farm to the problem.
prob_params.tidal_farm = farm

# Create the shallow water problem
problem = SWProblem(prob_params)

# Create a shallow water solver.
sol_params = CoupledSWSolver.default_parameters()
sol_params.dump_period = -1
sol_params.dolfin_solver["newton_solver"]["relative_tolerance"] = 1e-7
sol_params.dolfin_solver["newton_solver"]["maximum_iterations"] = 50
solver = CoupledSWSolver(problem, sol_params)

for s in solver.solve():
    print "Computed solution at time %f" % s["time"]
```

If I add the following lines under `solver = CoupledSWSolver(problem, sol_params)`, then it runs ok, but would this store the whole forward run in memory?

```
functional = PowerFunctional(problem)
control = TurbineFarmControl(farm)
rf_params = ReducedFunctional.default_parameters()
rf_params.automatic_scaling = 5
rf_params.save_checkpoints = True
rf_params.load_checkpoints = True
rf = ReducedFunctional(functional, control, solver, rf_params)
```

**Comment by funsim** [comment]
If you only want to run a forward model without adjoints, you can avoid storing the solution in memory by using

```python
for s in solver.solve(annotate=False):                                                                                                                                                                                                         
    print "Computed solution at time %f" % s["time"] 
```
