### ISSUE TITLE
Got error trying to run the examples

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#23]
Hi, I installed opentidalfarm with docker as you recommended, and tried to run the tidal simulation example for Orkney Island, but I encountered with some errors. First, I tried `mpirun -n 4 python tidal-simulation/orkney-coupled.py`, and I got the following error message:
```
Traceback (most recent call last):
  File "tidal-simulation/orkney-coupled.py", line 66, in <module>
    domain = FileDomain("../data/meshes/orkney/orkney_utm.xml")
  File "/usr/local/lib/python2.7/dist-packages/opentidalfarm/domains/file_domain.py", line 22, in __init__
    self.mesh = dolfin.Mesh(mesh_file)
  File "/usr/local/lib/python2.7/dist-packages/dolfin/mesh/meshes.py", line 63, in __init__
    cpp.Mesh.__cppinit__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dolfin/cpp/mesh.py", line 2066, in __init__
    _mesh.Mesh_swiginit(self, _mesh.new_Mesh(*args))
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to read data from XML file.
*** Reason:  Unable to open file "../data/meshes/orkney/orkney_utm.xml".
*** Where:   This error was encountered inside XMLFile.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2017.1.0
*** Git changeset:  3d1f687ec9ee39afc0fe6e01800431995b42ad04
*** -------------------------------------------------------------------------


===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 51 RUNNING AT 27e035d0a9de
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

Then I tried to run this example line by line in jupyter notebook and got stuck at 
```
eta_expr = TidalForcing(grid_file_name='../data/netcdf/gridES2008.nc',
                        data_file_name='../data/netcdf/hf.ES2008.nc',
                        ranges=((-4.0,0.0), (58.0,61.0)),
                        utm_zone=utm_zone,
                        utm_band=utm_band,
                        initial_time=datetime.datetime(2001, 9, 18, 10, 40),
                        constituents=['Q1', 'O1', 'P1', 'K1', 'N2', 'M2', 'S2', 'K2'], degree=2)
```
with the following error
```
IndexErrorTraceback (most recent call last)
<ipython-input-6-fe6aaa898d97> in <module>()
      5                         utm_band=utm_band,
      6                         initial_time=datetime.datetime(2001, 9, 18, 10, 40),
----> 7                         constituents=['Q1', 'O1', 'P1', 'K1', 'N2', 'M2', 'S2', 'K2'], degree=2)

/usr/local/lib/python2.7/dist-packages/dolfin/functions/expression.py in __init__(self, *args, **kwargs)
    282         # Calling the user defined_init
    283         if user_init is not None:
--> 284             user_init(self, *args, **kwargs)
    285 
    286         name = name or "f_" + str(ufl.Coefficient.count(self))

/usr/local/lib/python2.7/dist-packages/opentidalfarm/tidal.pyc in __init__(self, **kwargs)
     44         tide.set_initial_time(kwargs["initial_time"])
     45         self.tnci = uptide.tidal_netcdf.OTPSncTidalInterpolator(tide,
---> 46                     kwargs["grid_file_name"], kwargs["data_file_name"], kwargs["ranges"])
     47 
     48 

/usr/local/lib/python2.7/dist-packages/uptide/tidal_netcdf.pyc in OTPSncTidalInterpolator(tide, grid_file_name, data_file_name, ranges)
    210     # read grid, ranges and mask from grid netCDF
    211     tnci = TidalNetCDFInterpolator(tide, grid_file_name,
--> 212                                    ('nx', 'ny'), ('lon_z', 'lat_z'), ranges=ranges)
    213     if "mz" in tnci.nci.nc.variables:
    214         tnci.set_mask("mz")

/usr/local/lib/python2.7/dist-packages/uptide/tidal_netcdf.pyc in __init__(self, tide, grid_file_name, dimensions, coordinate_fields, ranges, mask)
     58         self.grid_file_name = grid_file_name
     59         self.nci = netcdf_reader.NetCDFInterpolator(grid_file_name, dimensions,
---> 60                                                     coordinate_fields)
     61 
     62         if ranges is not None:

/usr/local/lib/python2.7/dist-packages/uptide/netcdf_reader.pyc in __init__(self, filename, *args, **kwargs)
    250                 elif len(val.shape) == 2:
    251                     self.origin.append(val[0, 0])
--> 252                     self.delta.append(max(numpy.diff(val, axis=0).mean(),
    253                                       numpy.diff(val, axis=1).mean()))
    254                 else:

/usr/lib/python2.7/dist-packages/numpy/lib/function_base.pyc in diff(a, n, axis)
   1558     slice1 = [slice(None)]*nd
   1559     slice2 = [slice(None)]*nd
-> 1560     slice1[axis] = slice(1, None)
   1561     slice2[axis] = slice(None, -1)
   1562     slice1 = tuple(slice1)

IndexError: list assignment index out of range
```

**Comment by funsim** [comment]
Thanks, this is fixed in the latest Docker release. Update your Docker container with:

> fenicsproject pull quay.io/opentidalfarm/virtual

and try again.
