### ISSUE TITLE
Error in example 2.1

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#24]
Hi, I ran into an error when trying example 2.1. Could you take a look at the problem?
`python channel-simulation/channel-simulation.py`

```
Traceback (most recent call last):
  File "channel-simulation/channel-simulation.py", line 96, in <module>
    u_expr = Expression(("sin(pi*t/5)*x[1]*(50-x[1])/625", "0"), t=Constant(0))
  File "/usr/local/lib/python2.7/dist-packages/dolfin/functions/expression.py", line 157, in __init__
    element = _auto_select_element_from_shape(value_shape, degree, cell)
  File "/usr/local/lib/python2.7/dist-packages/dolfin/functions/expression.py", line 888, in _auto_select_element_from_shape
    raise TypeError("Expression needs an integer argument 'degree' if no 'element' is provided.")
TypeError: Expression needs an integer argument 'degree' if no 'element' is provided.
Aborted
```

**Comment by funsim** [comment]
Thanks, this is fixed in the latest Docker release. Update your Docker container with:

fenicsproject pull quay.io/opentidalfarm/virtual

and try again.
