### ISSUE TITLE
convert_to_new_xml.py script returns an error with example data

### ISSUE THREAD

**Issue by ArnoiZ** [OpenTidalFarm/OpenTidalFarm#27]
Hi, I am performing a similar tidal simulation as Example 2.3. In order to understand the input file, I am playing with the example Orkney mesh data.

Because the docker container doesn't include gmsh, I used gmsh in my system to convert `orkney_utm.geo` to `orkney_utm.msh`. And here's the return message.
```
Info    : Running 'gmsh -2 orkney_utm.geo' [Gmsh 4.2.2, 1 node, max. 1 thread]
Info    : Started on Thu Apr  4 14:49:19 2019
Info    : Reading 'orkney_utm.geo'...
Error   : 'orkney_utm.geo', line 4379 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4380 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4381 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4382 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4383 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4384 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4385 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4386 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4387 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4388 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4389 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4390 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4397 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : 'orkney_utm.geo', line 4398 : Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Curve { ... };
Error   : Unknown curve 2189
Error   : Unknown number option 'Mesh.RemeshAlgorithm'
Info    : Done reading 'orkney_utm.geo'
Info    : Meshing 1D...
Info    : Meshing curve 1/2219 (Line)
Info    : Meshing curve 1001/2219 (Line)
Info    : Meshing curve 2001/2219 (Line)
Info    : Done meshing 1D (1.68199 s)
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Delaunay)
Warning : Mesh generation of surface 1 skipped: only 0 nodes on the boundary
Warning : Surface 1 consists of no elements
Info    : Meshing surface 12602 (Plane, Delaunay)
Info    : Meshing surface 12604 (Plane, Delaunay)
Info    : Meshing surface 12606 (Plane, Delaunay)
Info    : Meshing surface 12608 (Plane, Delaunay)
Info    : Done meshing 2D (0.004799 s)
Info    : 3228 vertices 5619 elements
Warning : ------------------------------
Warning : Mesh generation error summary
Warning :     2 warnings
Warning :     0 errors
Warning : Check the full log for details
Warning : ------------------------------
Info    : Writing 'orkney_utm.msh'...
Info    : Done writing 'orkney_utm.msh'
Info    : Stopped on Thu Apr  4 14:49:20 2019
```

Then, I tried to use `dolfin-convert` in the docker container to convert `.msh` to `.xml`. However, I get the following error message.
```
Converting from Gmsh format (.msh, .gmsh) to DOLFIN XML format
Traceback (most recent call last):
  File "/usr/local/bin/dolfin-convert", line 132, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/dolfin-convert", line 79, in main
    meshconvert.convert2xml(ifilename, ofilename, iformat=iformat)
  File "/usr/local/lib/python2.7/dist-packages/dolfin_utils/meshconvert/meshconvert.py", line 1299, in convert2xml
    convert(ifilename, XmlHandler(ofilename), iformat=iformat)
  File "/usr/local/lib/python2.7/dist-packages/dolfin_utils/meshconvert/meshconvert.py", line 1320, in convert
    gmsh2xml(ifilename, handler)
  File "/usr/local/lib/python2.7/dist-packages/dolfin_utils/meshconvert/meshconvert.py", line 272, in gmsh2xml
    num_elements = int(line)
ValueError: invalid literal for int() with base 10: '13 1017 1 1017\n'
```

Could you take a look at this problem? Thank you.

Best regards,

Ming

**Comment by funsim** [comment]
Hi Ming,

I have now updated the docker container so that it includes gmsh and the converion script. Can you try again? You should be able to generate the meshes all within the docker now.

(Don't forget to update your container with
```
fenicsproject pull quay.io/opentidalfarm/virtual
```
)
